### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by fschutt** [SimonSapin/rust-forest#6]
The library has changed a lot and the crates.io version hasn't been updated in a while. If possible, please release a new version of the library so that other libraries can depend on it (crates.io requires no links to github projects as dependencies). Thanks.

**Comment by SimonSapin** [comment]
I wouldn’t call “changed a lot” three commits since 2015, but regardless I’m not planning to maintain this code. I’ve added a section to the README to explain this. If you’d like to use this code, consider copying it into your repo.

**Comment by fschutt** [comment]
Yes, but you yanked the crate from crates.io for some reason. Why? I'd just leave it up.

**Comment by SimonSapin** [comment]
I yanked it so that people wouldn’t depend on it. I don’t want people to depend on it because I don’t want to deal with reviewing PRs and publishing new versions. If you want to do that, feel free to do it in another repository. The code’s still open-source.
