### ISSUE TITLE
rctree crate ownership

### ISSUE THREAD

**Issue by RazrFalcon** [SimonSapin/rust-forest#8]
Hi. I made a [rctree fork](https://github.com/RazrFalcon/rctree) and plan to support it in the future.

It would be great if you could transfer [rctree crate](https://crates.io/crates/rctree) ownership to me. I don't want to create `rctree2` or something... Especially because the current one was yanked.

My fork isn't a 100% copy, it has some changed: https://github.com/RazrFalcon/rctree#differences

**Comment by SimonSapin** [comment]
Done!

> user RazrFalcon has been invited to be an owner of crate rctree

**Comment by RazrFalcon** [comment]
Thanks!
